language: python
python:
  - 2.6
  - 2.7
install:
  - pip install -r requirements.txt --use-mirrors
script:
  nosetests --cover-branches --cover-package=tests --with-coverage test
after_success:
  coveralls
